version: "3"
services:
  cloudscraper-proxy-service:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      # - ./promtail-config.yml:/etc/promtail/config.yml
      # - ./default-config.yml:/opt/cloudscraper-proxy/config.yml
      # - ./supervisord.conf:/etc/supervisor/supervisord.conf
      - logs:/opt/cloudscraper-proxy/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

volumes:
  logs:
