name: Python Flask CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHONPATH: ${{ github.workspace }}/service
  MEINHELD_NOGREEN: 1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r service/requirements.txt
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./service"
      - name: Unit tests coverage
        run: |
          coverage run -m unittest discover service/tests/
          coverage report
          coverage xml -o coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
